In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
weather_df = pd.read_csv('weather_4provinces_daily_2021_2025.csv')
weather_df.head()

,Date,Province,Role,Temperature_C,Rainfall_mm,Humidity_Percent,Soil_Moisture
0,1/1/2021,PathumThani_Hub,Market_Consumer,22.08,0.0,52.29,0.29
1,2/1/2021,PathumThani_Hub,Market_Consumer,22.73,0.0,52.92,0.29
2,3/1/2021,PathumThani_Hub,Market_Consumer,24.00,0.0,56.33,0.29
3,4/1/2021,PathumThani_Hub,Market_Consumer,25.47,0.0,58.04,0.29
4,5/1/2021,PathumThani_Hub,Market_Consumer,26.65,0.0,58.83,0.29

In [30]:
weather_wide = weather_df.pivot(
    index='Date',
    columns='Province',
    values=['Temperature_C', 'Rainfall_mm', 'Humidity_Percent', 'Soil_Moisture']
)

new_names = []
for col in weather_wide.columns:
    variable_name = col[0]
    province_name = col[1]

    full_name = f"{province_name}_{variable_name}"

    new_names.append(full_name)

weather_wide.columns = new_names

weather_wide.head()

,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,PathumThani_Hub_Humidity_Percent,Phetchabun_High_Humidity_Percent,Ratchaburi_Veg_Humidity_Percent,NakhonPathom_Meat_Soil_Moisture,PathumThani_Hub_Soil_Moisture,Phetchabun_High_Soil_Moisture,Ratchaburi_Veg_Soil_Moisture
Date,,,,,,,,,,,,,,,,
1/1/2021,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,52.29,47.04,55.54,0.17,0.29,0.26,0.19
1/1/2022,25.30,25.51,24.03,24.98,0.0,0.0,0.0,0.0,59.79,57.88,57.25,63.42,0.18,0.29,0.26,0.17
1/1/2023,23.31,23.98,22.35,22.73,0.0,0.0,0.0,0.0,59.88,55.79,53.46,66.21,0.19,0.29,0.28,0.22
1/1/2024,28.35,28.21,26.41,27.95,0.0,0.0,0.0,0.0,61.71,63.00,58.83,63.71,0.16,0.31,0.27,0.16
1/1/2025,24.89,26.30,23.73,24.53,0.0,0.0,0.0,0.0,60.38,52.62,55.88,64.00,0.19,0.19,0.23,0.17

In [31]:
weather_wide = weather_wide.reset_index()
weather_wide['Date'] = weather_wide['Date'].astype(str)

temp_split = weather_wide['Date'].str.split('/', expand=True)

weather_wide['Day'] = temp_split[0].astype(int)
weather_wide['Month'] = temp_split[1].astype(int)
weather_wide['Year'] = temp_split[2].astype(int)

temp_date = pd.to_datetime(weather_wide[['Year', 'Month', 'Day']])
weather_wide['DayOfWeek_Num'] = temp_date.dt.dayofweek
weather_wide.head()

,Date,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,...,Phetchabun_High_Humidity_Percent,Ratchaburi_Veg_Humidity_Percent,NakhonPathom_Meat_Soil_Moisture,PathumThani_Hub_Soil_Moisture,Phetchabun_High_Soil_Moisture,Ratchaburi_Veg_Soil_Moisture,Day,Month,Year,DayOfWeek_Num
0,1/1/2021,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,...,47.04,55.54,0.17,0.29,0.26,0.19,1,1,2021,4
1,1/1/2022,25.30,25.51,24.03,24.98,0.0,0.0,0.0,0.0,59.79,...,57.25,63.42,0.18,0.29,0.26,0.17,1,1,2022,5
2,1/1/2023,23.31,23.98,22.35,22.73,0.0,0.0,0.0,0.0,59.88,...,53.46,66.21,0.19,0.29,0.28,0.22,1,1,2023,6
3,1/1/2024,28.35,28.21,26.41,27.95,0.0,0.0,0.0,0.0,61.71,...,58.83,63.71,0.16,0.31,0.27,0.16,1,1,2024,0
4,1/1/2025,24.89,26.30,23.73,24.53,0.0,0.0,0.0,0.0,60.38,...,55.88,64.00,0.19,0.19,0.23,0.17,1,1,2025,2

In [32]:
weather_wide.to_csv('weather_data.csv', index=False)

Diesel

In [33]:
df_oil2564 = pd.read_csv('./dataset/oil_2564.csv', header=1)
df_oil2565 = pd.read_csv('./dataset/oil_2565.csv', header=1)
df_oil2566 = pd.read_csv('./dataset/oil_2566.csv', header=1)
df_oil2567 = pd.read_csv('./dataset/oil_2567.csv', header=1)
df_oil2568 = pd.read_csv('./dataset/oil_2568.csv', header=1)

In [34]:
diesel_data = pd.concat([df_oil2564, df_oil2565, df_oil2566, df_oil2567, df_oil2568], ignore_index=True)
diesel_data = diesel_data.rename(columns={'Unnamed: 0': 'Date', 'ไฮดีเซล': 'Diesel'})
diesel_data = diesel_data[['Date', 'Diesel']]
diesel_data.head()

         Date  Diesel
0  24/12/2564   28.44
1  22/12/2564   28.04
2  15/12/2564   28.44
3  10/12/2564   28.24
4   2/12/2564   27.84

In [ ]:
diesel_data['Date'] = diesel_data['Date'].astype(str)

temp_split = diesel_data['Date'].str.split('/', expand=True)

diesel_data['Day'] = temp_split[0].astype(int)
diesel_data['Month'] = temp_split[1].astype(int)
diesel_data['Year'] = temp_split[2].astype(int)

diesel_data['Year'] = diesel_data['Year'] - 543


diesel_data.head()

         Date  Diesel  Day  Month  Year
0  24/12/2564   28.44   24     12  2021
1  22/12/2564   28.04   22     12  2021
2  15/12/2564   28.44   15     12  2021
3  10/12/2564   28.24   10     12  2021
4   2/12/2564   27.84    2     12  2021

In [36]:
temp_date = pd.to_datetime(diesel_data[['Year', 'Month', 'Day']])
diesel_data['DayOfWeek_Num'] = temp_date.dt.dayofweek
# diesel_data = diesel_data.drop(columns=['Date'])
diesel_data.head()

         Date  Diesel  Day  Month  Year  DayOfWeek_Num
0  24/12/2564   28.44   24     12  2021              4
1  22/12/2564   28.04   22     12  2021              2
2  15/12/2564   28.44   15     12  2021              2
3  10/12/2564   28.24   10     12  2021              4
4   2/12/2564   27.84    2     12  2021              3

In [37]:
diesel_data.to_csv('cleaned_oil_data.csv', index=False)

Merge data weather and diesel

In [38]:
weather_df = pd.read_csv('weather_data.csv')
diesel_df = pd.read_csv('cleaned_oil_data.csv')

In [39]:
diesel_df.head()

         Date  Diesel  Day  Month  Year  DayOfWeek_Num
0  24/12/2564   28.44   24     12  2021              4
1  22/12/2564   28.04   22     12  2021              2
2  15/12/2564   28.44   15     12  2021              2
3  10/12/2564   28.24   10     12  2021              4
4   2/12/2564   27.84    2     12  2021              3

In [40]:
weather_df.head()

,Date,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,...,Phetchabun_High_Humidity_Percent,Ratchaburi_Veg_Humidity_Percent,NakhonPathom_Meat_Soil_Moisture,PathumThani_Hub_Soil_Moisture,Phetchabun_High_Soil_Moisture,Ratchaburi_Veg_Soil_Moisture,Day,Month,Year,DayOfWeek_Num
0,1/1/2021,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,...,47.04,55.54,0.17,0.29,0.26,0.19,1,1,2021,4
1,1/1/2022,25.30,25.51,24.03,24.98,0.0,0.0,0.0,0.0,59.79,...,57.25,63.42,0.18,0.29,0.26,0.17,1,1,2022,5
2,1/1/2023,23.31,23.98,22.35,22.73,0.0,0.0,0.0,0.0,59.88,...,53.46,66.21,0.19,0.29,0.28,0.22,1,1,2023,6
3,1/1/2024,28.35,28.21,26.41,27.95,0.0,0.0,0.0,0.0,61.71,...,58.83,63.71,0.16,0.31,0.27,0.16,1,1,2024,0
4,1/1/2025,24.89,26.30,23.73,24.53,0.0,0.0,0.0,0.0,60.38,...,55.88,64.00,0.19,0.19,0.23,0.17,1,1,2025,2

In [41]:
weather_df['Date_Match'] = pd.to_datetime(weather_df[['Year', 'Month', 'Day']])
diesel_df['Date_Match'] = pd.to_datetime(diesel_df[['Year', 'Month', 'Day']])

In [47]:
merge01_df = pd.merge(
    weather_df, 
    diesel_df[['Date_Match', 'Diesel']], 
    on='Date_Match', 
    how='left'
)


merge01_df.head()

,Date,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,...,NakhonPathom_Meat_Soil_Moisture,PathumThani_Hub_Soil_Moisture,Phetchabun_High_Soil_Moisture,Ratchaburi_Veg_Soil_Moisture,Day,Month,Year,DayOfWeek_Num,Date_Match,Diesel
0,1/1/2021,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,...,0.17,0.29,0.26,0.19,1,1,2021,4,2021-01-01,NaN
1,1/1/2022,25.30,25.51,24.03,24.98,0.0,0.0,0.0,0.0,59.79,...,0.18,0.29,0.26,0.17,1,1,2022,5,2022-01-01,NaN
2,1/1/2023,23.31,23.98,22.35,22.73,0.0,0.0,0.0,0.0,59.88,...,0.19,0.29,0.28,0.22,1,1,2023,6,2023-01-01,NaN
3,1/1/2024,28.35,28.21,26.41,27.95,0.0,0.0,0.0,0.0,61.71,...,0.16,0.31,0.27,0.16,1,1,2024,0,2024-01-01,NaN
4,1/1/2025,24.89,26.30,23.73,24.53,0.0,0.0,0.0,0.0,60.38,...,0.19,0.19,0.23,0.17,1,1,2025,2,2025-01-01,NaN

In [48]:
merge01_df = merge01_df.drop(columns=['Date'])
merge01_df.to_csv('merge01_data.csv', index=False)

Forward fill diesel

In [49]:
sorted_df = pd.read_csv('merge01_data.csv')

In [51]:
sorted_df = merge01_df.sort_values(by='Date_Match')

In [ ]:

sorted_df["Diesel"] = sorted_df["Diesel"].ffill()
sorted_df["Diesel"] = sorted_df["Diesel"].bfill()


sorted_df.head()

,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,PathumThani_Hub_Humidity_Percent,...,NakhonPathom_Meat_Soil_Moisture,PathumThani_Hub_Soil_Moisture,Phetchabun_High_Soil_Moisture,Ratchaburi_Veg_Soil_Moisture,Day,Month,Year,DayOfWeek_Num,Date_Match,Diesel
0,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,52.29,...,0.17,0.29,0.26,0.19,1,1,2021,4,2021-01-01,24.19
660,22.67,22.73,19.56,22.27,0.0,0.0,0.0,0.0,52.29,52.92,...,0.17,0.29,0.26,0.19,2,1,2021,5,2021-01-02,24.19
1317,23.85,24.00,21.00,23.27,0.0,0.0,0.0,0.0,54.88,56.33,...,0.17,0.29,0.27,0.19,3,1,2021,6,2021-01-03,24.19
1467,25.20,25.47,23.21,24.61,0.0,0.0,0.0,0.0,57.83,58.04,...,0.16,0.29,0.26,0.18,4,1,2021,0,2021-01-04,24.19
1527,26.45,26.65,24.98,25.99,0.0,0.0,0.0,0.0,60.62,58.83,...,0.16,0.29,0.26,0.18,5,1,2021,1,2021-01-05,24.19

In [58]:
sorted_df.to_csv('merge02_data.csv', index=False)

Ingredient dataset cleaning

In [ ]:
merge02_data = pd.read_csv('merge02_data.csv')
merge02_data['Date_Match'] = pd.to_datetime(merge02_data['Date_Match'])

files = ["chicken", "chili", "coriander", "egg", "garlic", "lime", "onion", "peanut", "pork",
         "shallot", "shrimp", "spring_onion", "tamarind_juice"]

for i in files:    

    loop_data = pd.read_csv(f'./dataset/ingredient/{i}.csv')

    loop_data['วันที่'] = loop_data['วันที่'].replace('29 ก.พ. 2567', '29/2/2567')
    loop_data = loop_data.rename(columns={'ราคาเฉลี่ย': f'Price_{i}'})
    

    loop_data['Date'] = loop_data['วันที่'].astype(str)

    temp_split = loop_data['Date'].str.split('/', expand=True)

    loop_data['Day'] = temp_split[0].astype(int)
    loop_data['Month'] = temp_split[1].astype(int)
    loop_data['Year'] = temp_split[2].astype(int) - 543
    

    loop_data['Date_Match'] = pd.to_datetime(loop_data[['Year', 'Month', 'Day']])

    loop_data_clean = loop_data[[f'Price_{i}', 'Date_Match']]

    merge02_data = pd.merge(
                merge02_data, 
                loop_data_clean, 
                on='Date_Match', 
                how='left'
                )

In [90]:
merge02_data.head()
merge02_data.to_csv('merge03_df.csv', index=False)

Forward Fill ingredient proce

In [91]:
ingredient_df = pd.read_csv('merge03_df.csv')
ingredient_df.head()

,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,PathumThani_Hub_Humidity_Percent,...,Price_egg,Price_garlic,Price_lime,Price_onion,Price_peanut,Price_pork,Price_shallot,Price_shrimp,Price_spring_onion,Price_tamarind_juice
0,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,52.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22.67,22.73,19.56,22.27,0.0,0.0,0.0,0.0,52.29,52.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23.85,24.00,21.00,23.27,0.0,0.0,0.0,0.0,54.88,56.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25.20,25.47,23.21,24.61,0.0,0.0,0.0,0.0,57.83,58.04,...,3.05,82.5,2.25,NaN,70.0,162.5,105.0,225.0,NaN,95.0
4,26.45,26.65,24.98,25.99,0.0,0.0,0.0,0.0,60.62,58.83,...,3.05,82.5,2.25,NaN,70.0,162.5,105.0,225.0,NaN,95.0

In [92]:
ingredient_df.columns

Index(['NakhonPathom_Meat_Temperature_C', 'PathumThani_Hub_Temperature_C',
       'Phetchabun_High_Temperature_C', 'Ratchaburi_Veg_Temperature_C',
       'NakhonPathom_Meat_Rainfall_mm', 'PathumThani_Hub_Rainfall_mm',
       'Phetchabun_High_Rainfall_mm', 'Ratchaburi_Veg_Rainfall_mm',
       'NakhonPathom_Meat_Humidity_Percent',
       'PathumThani_Hub_Humidity_Percent', 'Phetchabun_High_Humidity_Percent',
       'Ratchaburi_Veg_Humidity_Percent', 'NakhonPathom_Meat_Soil_Moisture',
       'PathumThani_Hub_Soil_Moisture', 'Phetchabun_High_Soil_Moisture',
       'Ratchaburi_Veg_Soil_Moisture', 'Day', 'Month', 'Year', 'DayOfWeek_Num',
       'Date_Match', 'Diesel', 'Price_chicken', 'Price_chili',
       'Price_coriander', 'Price_egg', 'Price_garlic', 'Price_lime',
       'Price_onion', 'Price_peanut', 'Price_pork', 'Price_shallot',
       'Price_shrimp', 'Price_spring_onion', 'Price_tamarind_juice'],
      dtype='object')

In [95]:
names =  ['Price_chicken', 'Price_chili', 'Price_coriander', 'Price_egg', 'Price_garlic', 'Price_lime',
       'Price_onion', 'Price_peanut', 'Price_pork', 'Price_shallot',
       'Price_shrimp', 'Price_spring_onion', 'Price_tamarind_juice']

ingredient_df = ingredient_df.sort_values(by='Date_Match')

for i in names:
    

    ingredient_df[i] = ingredient_df[i].ffill()
    ingredient_df[i] = ingredient_df[i].bfill()


ingredient_df.head()

,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,PathumThani_Hub_Humidity_Percent,...,Price_egg,Price_garlic,Price_lime,Price_onion,Price_peanut,Price_pork,Price_shallot,Price_shrimp,Price_spring_onion,Price_tamarind_juice
0,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,52.29,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
1,22.67,22.73,19.56,22.27,0.0,0.0,0.0,0.0,52.29,52.92,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
2,23.85,24.00,21.00,23.27,0.0,0.0,0.0,0.0,54.88,56.33,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
3,25.20,25.47,23.21,24.61,0.0,0.0,0.0,0.0,57.83,58.04,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
4,26.45,26.65,24.98,25.99,0.0,0.0,0.0,0.0,60.62,58.83,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0

In [97]:
ingredient_df.to_csv('merge04_df.csv', index=False)

Combine with Holiday dataset

In [143]:
holiday_df = pd.read_csv('merge_calendar_2021_2025.csv')
holiday_df.head()

,Date,Day_Name,Month_Name,Year,Important_Events,Day_Type,Important_Days
0,1/1/2021,Friday,January,2021,New Year's Day,Yes,1
1,2/1/2021,Saturday,January,2021,NaN,Weekend,0
2,3/1/2021,Sunday,January,2021,NaN,Weekend,0
3,4/1/2021,Monday,January,2021,NaN,No,0
4,5/1/2021,Tuesday,January,2021,NaN,No,0

In [144]:
holiday_df = holiday_df[['Date', 'Important_Days']]
holiday_df = holiday_df.rename(columns={'Date': 'Date_Match'})
holiday_df['Date_Match'] = pd.to_datetime(holiday_df['Date_Match'], format='%d/%m/%Y')
holiday_df.head()

  Date_Match  Important_Days
0 2021-01-01               1
1 2021-01-02               0
2 2021-01-03               0
3 2021-01-04               0
4 2021-01-05               0

In [145]:
merge04_df = pd.read_csv('merge04_df.csv')
merge04_df['Date_Match'] = pd.to_datetime(merge04_df['Date_Match'])
merge04_df.head()

,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,PathumThani_Hub_Humidity_Percent,...,Price_egg,Price_garlic,Price_lime,Price_onion,Price_peanut,Price_pork,Price_shallot,Price_shrimp,Price_spring_onion,Price_tamarind_juice
0,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,52.29,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
1,22.67,22.73,19.56,22.27,0.0,0.0,0.0,0.0,52.29,52.92,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
2,23.85,24.00,21.00,23.27,0.0,0.0,0.0,0.0,54.88,56.33,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
3,25.20,25.47,23.21,24.61,0.0,0.0,0.0,0.0,57.83,58.04,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0
4,26.45,26.65,24.98,25.99,0.0,0.0,0.0,0.0,60.62,58.83,...,3.05,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0

In [146]:
merge04_df = pd.merge(
                merge04_df, 
                holiday_df, 
                on='Date_Match', 
                how='left'
                )

In [ ]:
merge04_df.head()

,NakhonPathom_Meat_Temperature_C,PathumThani_Hub_Temperature_C,Phetchabun_High_Temperature_C,Ratchaburi_Veg_Temperature_C,NakhonPathom_Meat_Rainfall_mm,PathumThani_Hub_Rainfall_mm,Phetchabun_High_Rainfall_mm,Ratchaburi_Veg_Rainfall_mm,NakhonPathom_Meat_Humidity_Percent,PathumThani_Hub_Humidity_Percent,...,Price_garlic,Price_lime,Price_onion,Price_peanut,Price_pork,Price_shallot,Price_shrimp,Price_spring_onion,Price_tamarind_juice,Important_Days
0,22.12,22.08,19.99,21.70,0.0,0.0,0.0,0.0,50.83,52.29,...,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0,1
1,22.67,22.73,19.56,22.27,0.0,0.0,0.0,0.0,52.29,52.92,...,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0,0
2,23.85,24.00,21.00,23.27,0.0,0.0,0.0,0.0,54.88,56.33,...,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0,0
3,25.20,25.47,23.21,24.61,0.0,0.0,0.0,0.0,57.83,58.04,...,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0,0
4,26.45,26.65,24.98,25.99,0.0,0.0,0.0,0.0,60.62,58.83,...,82.5,2.25,35.0,70.0,162.5,105.0,225.0,85.0,95.0,0

In [149]:
merge04_df.to_csv('final_df.csv', index=False)